version: "0.2"
phases:
    build:
        commands:
            - aws s3 cp s3://$S3_BUCKET_NAME/adf-build/ adf-build/ --recursive --quiet
            - pip install --upgrade pip
            - pip install -r adf-build/requirements.txt -q
            - python adf-build/generate_params.py
artifacts:
    files:
        - "**/*"
